# Generated by Django 5.2.2 on 2025-06-08 09:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='users/avatars/', verbose_name='Изображение аватара'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Никнейм пользователя может содержать только буквы, цифры и символы: . @ + - _', regex='^[\\w.@+-]+$')], verbose_name='Никнейм'),
        ),
    ]
