# Generated by Django 5.2.2 on 2025-06-09 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
        ('users', '0009_user_is_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_in_favorite', to='recipes.recipe', verbose_name='Рецепт'),
        ),
    ]
